apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "web-kub.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "web-kub.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "labels.standard" . | indent 8 }}
    spec:
      volumes:
      - name: homevol
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "web-kub.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      hostname: web-kub
      serviceAccountName: {{ .Values.serviceaccount }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: USERNAME
            value : "{{ .Values.ssh.username }}"
          - name: PASSWORD
            value : "{{ .Values.ssh.password }}"
          - name: AUTO_KUBERNETES_CONFIG
            value : "{{ .Values.kubeconfig }}"
          ports:
            - name: http
              containerPort: 5688
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 5688
          readinessProbe:
            httpGet:
              path: /
              port: 5688
          volumeMounts:
          - mountPath: /home/
            name: homevol
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
