apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-kub.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 8 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5688
      protocol: TCP
      name: http
  selector:
    app: {{ include "web-kub.name" . }}
    release: {{ .Release.Name }}
