---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webkubsrvaccount
  namespace: web-kub
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: webkub-clusterrole
rules:
# Just an example, feel free to change it
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: webkub-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: webkubsrvaccount
  namespace: web-kub
roleRef:
  kind: ClusterRole
  name: webkub-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
## for pod exec commands
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: webkub-pod-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: webkub-pod-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: webkubsrvaccount
  namespace: web-kub
roleRef:
  kind: ClusterRole
  name: webkub-pod-clusterrole
  apiGroup: rbac.authorization.k8s.io