{{- if .Values.secretfiles.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web-kubectl.fullname" . }}-file
  labels:
    {{- include "web-kubectl.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.envAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- toYaml .Values.secretfiles.secretFile | nindent 2 }}
{{- end }}