{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web-kubectl.fullname" . }}
  labels:
    {{- include "web-kubectl.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.envAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets.secretData | nindent 2 }}
{{- end }}